# Generated by Django 5.0.6 on 2024-07-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ControlObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "planned_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "actual_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("unit", models.CharField(max_length=50)),
                ("planned_start_date", models.DateField()),
                ("planned_finish_date", models.DateField()),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_finish_date", models.DateField(blank=True, null=True)),
                ("total_float", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "threshold_time",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "threshold_cost",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("site_condition", models.CharField(max_length=255)),
                ("weather", models.CharField(max_length=255)),
                ("congestion", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Predecessor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lag", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "quantity_completed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Allocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "craft",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resource.craft",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resource.equipment",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resource.material",
                    ),
                ),
                (
                    "sub_contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="resource.subcontractor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
