# Generated by Django 5.0.6 on 2024-07-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("control", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="controlobject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="control_objects",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="allocation",
            name="control_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="control.controlobject",
            ),
        ),
        migrations.AddField(
            model_name="predecessor",
            name="control_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="predecessors",
                to="control.controlobject",
            ),
        ),
        migrations.AddField(
            model_name="predecessor",
            name="predecessor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successors",
                to="control.controlobject",
            ),
        ),
        migrations.AddField(
            model_name="progress",
            name="control_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_records",
                to="control.controlobject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="controlobject",
            unique_together={("project", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="predecessor",
            unique_together={("control_object", "predecessor")},
        ),
        migrations.AlterUniqueTogether(
            name="progress",
            unique_together={("control_object", "date")},
        ),
    ]
