# Generated by Django 5.0.6 on 2024-07-07 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("company", "0001_initial"),
        ("employee_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("project_code", models.CharField(max_length=50, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RESIDENTIAL", "Residential"),
                            ("COMMERCIAL", "Commercial"),
                            ("INDUSTRIAL", "Industrial"),
                            ("INFRASTRUCTURE", "Infrastructure"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=15)),
                ("plan_start_date", models.DateField()),
                ("plan_finish_date", models.DateField()),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_finish_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(default="PLANNING", max_length=20)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-plan_start_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectManager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(max_length=50)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="project.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee_management.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "project")},
            },
        ),
    ]
