# Generated by Django 5.0.6 on 2024-07-08 00:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
        ("project", "0002_project_end_date_project_percent_complete_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-start_date"]},
        ),
        migrations.RemoveField(
            model_name="project",
            name="plan_finish_date",
        ),
        migrations.RemoveField(
            model_name="project",
            name="plan_start_date",
        ),
        migrations.AddField(
            model_name="task",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="company.company"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
